- name: Restart kube-service-catalog
  shell: "oc --config=../kubeconfig delete pods --all -n kube-service-catalog"
  listen: "kscRestart"

- name: Wait for kube-service-catalog pods to be Running
  shell: "oc --config=../kubeconfig get pods -n kube-service-catalog |grep -i Running"
  register: oc_get_pods
  until: "'Running' in oc_get_pods.stdout and 'deploy' not in oc_get_pods.stdout"
  retries: 60
  delay: 2
  listen: "kscRestart"

