---

- hosts: localhost
  gather_facts: false
  become: true

  tasks:


  - name: copy kubeconfig
    fetch:
      src: /root/.kube/config
      dest: ../kubeconfig
      flat: yes
    delegate_to: "{{groups['masters'] | first}}"

- hosts: localhost
  gather_facts: false
  become: false

  roles:
  - ocppost 


- hosts: masters
  gather_facts: false
  become: true

 
  tasks:

  - name: update master config yaml with project request limits
    blockinfile:
      insertafter: "pluginConfig"
      path: /etc/origin/master/master-config.yaml
      block: |2
            ProjectRequestLimit:
              configuration:
                  apiVersion: v1
                  kind: ProjectRequestLimitConfig
                  limits:
                  - selector:
                          level: admin
                  - maxProjects: 0
    register: blockupdate

  - name: node check | insure workaround in place for pods restarts
    shell:  'echo -e "r /etc/cni/net.d/80-openshift-network.conf\nr /etc/origin/openvswitch/conf.db"  > /usr/lib/tmpfiles.d/cleanup-cni.conf'
    when: blockupdate.changed == True

  - name: node check | reboot node
    reboot:
    when: blockupdate.changed == True

  - name: node check | wait for node to appear as ready
    shell: "oc --config=../kubeconfig get nodes |grep -i {{hostname}}|grep -i Ready"
    become: false
    register: oc_node_ready
    until: "'NotReady' not in oc_node_ready.stdout and 'Ready' in oc_node_ready.stdout"
    retries: 60
    delay: 2
    delegate_to: localhost
    when: blockupdate.changed == True
